"""Golden-vector generator — the Python reference build is the oracle.

Imports the LIVE game modules and executes them to produce conformance
fixtures for the C# port (Game1.Core.Tests). Never hand-derives a formula
where the real code path can be executed; the two fixtures that transcribe
inline code (defense_reduction, damage_composition) say so in _meta and are
superseded by crux-foundry scenario parity in Phase 4.

Usage:  python Game-1-Godot/conformance/generate_goldens.py
Output: Game-1-Godot/conformance/goldens/*.json  (committed)
"""
import json
import os
import subprocess
import sys
from datetime import date
from pathlib import Path
from types import SimpleNamespace

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
SRC = REPO / "Game-1-modular"
OUT = HERE / "goldens"

# Game modules print emoji; the Windows console defaults to cp1252.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

os.environ.setdefault("SDL_VIDEODRIVER", "dummy")
os.environ.setdefault("SDL_AUDIODRIVER", "dummy")
# Goldens pin the SHIPPED defaults, not a tuning-session override.
for _var in ("CRUX_LCK_CRIT_PER_POINT", "CRUX_STR_DMG_PER_POINT"):
    os.environ.pop(_var, None)
sys.path.insert(0, str(SRC))
os.chdir(SRC)  # content JSON paths resolve relative to the game root


def git_sha() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"], cwd=REPO,
            capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"


SHA = git_sha()


def meta(source: str, note: str = "") -> dict:
    m = {"generated": date.today().isoformat(), "git_sha": SHA, "source": source,
         "doctrine": "generated by executing the live Python modules"}
    if note:
        m["note"] = note
    return m


def write(name: str, payload: dict) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / name
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, sort_keys=True)
    print(f"  wrote {path.relative_to(REPO)}")


# ── 1. EXP curve + cascade semantics ─────────────────────────────────────────
def gen_exp_curve() -> None:
    from entities.components.leveling import LevelingSystem

    ls = LevelingSystem()
    requirements = {str(lvl): ls.exp_requirements[lvl] for lvl in ls.exp_requirements}
    cumulative, total = {}, 0
    for lvl in range(2, ls.max_level + 1):
        total += ls.exp_requirements[lvl]
        cumulative[str(lvl)] = total

    def scenario(grants):
        s = LevelingSystem()
        results = []
        for amount in grants:
            leveled = s.add_exp(amount)
            results.append({"grant": amount, "leveled": leveled,
                            "level": s.level, "current_exp": s.current_exp,
                            "unallocated_stat_points": s.unallocated_stat_points})
        return results

    scenarios = {
        "single_grants": [scenario([a]) for a in
                          [0, 199, 200, 201, 349, 350, 550, 1000, 5000, 100000, 10**9]],
        "sequential": scenario([200, 350, 613, 100, 5000, 250000]),
        "max_level_clamp": scenario([10**10, 500]),
    }
    write("exp_curve.json", {
        "_meta": meta("entities/components/leveling.py::LevelingSystem"),
        "max_level": ls.max_level,
        "requirements_to_reach_level": requirements,
        "cumulative_from_level_1": cumulative,
        "cascade_scenarios": scenarios,
    })


# ── 2. Stat scaling (JSON-driven, executed through CharacterStats) ───────────
def gen_stat_scaling() -> None:
    import entities.components.stats as stats_mod
    from entities.components.stats import CharacterStats

    stat_names = ["strength", "defense", "vitality", "luck", "agility", "intelligence"]
    levels = list(range(0, 31))

    percent = {s: {str(v): CharacterStats(**{s: v}).get_bonus(s) for v in levels}
               for s in stat_names}
    flat = {}
    for s, bonuses in stats_mod._FLAT_BONUSES.items():
        flat[s] = {bt: {str(v): CharacterStats(**{s: v}).get_flat_bonus(s, bt)
                        for v in [0, 1, 10, 30]} for bt in bonuses}

    multipliers = {
        "durability_loss_by_def": {str(v): CharacterStats(defense=v).get_durability_loss_multiplier()
                                   for v in [0, 10, 30, 45, 50, 100]},
        "durability_bonus_by_vit": {str(v): CharacterStats(vitality=v).get_durability_bonus_multiplier()
                                    for v in [0, 10, 30]},
        "carry_capacity_by_str": {str(v): CharacterStats(strength=v).get_carry_capacity_multiplier()
                                  for v in [0, 10, 30]},
    }
    eff_luck = [{"luck": l, "title": t, "skill": s, "rare_drop": r,
                 "effective": CharacterStats(luck=l).get_effective_luck(t, s, r)}
                for (l, t, s, r) in [(0, 0, 0, 0), (10, 0, 0, 0), (10, 5, 0, 0),
                                     (10, 0, 3, 0), (10, 0, 0, 0.15), (30, 5, 3, 0.15)]]
    write("stat_scaling.json", {
        "_meta": meta("entities/components/stats.py (scaling resolved from "
                      "Definitions.JSON/stats-calculations.JSON with code fallbacks)"),
        "resolved_scaling": stats_mod._SCALING,
        "resolved_flat_bonuses": stats_mod._FLAT_BONUSES,
        "percent_bonus": percent,
        "flat_bonus": flat,
        "multipliers": multipliers,
        "effective_luck": eff_luck,
    })


# ── 3. Crit chance — executes the REAL _player_crit_chance on a shim ─────────
def gen_crit_chance() -> None:
    from Combat.combat_manager import CombatManager, _LCK_CRIT_PER_POINT

    class Buffs:
        def __init__(self, pierce): self.pierce = pierce
        def get_total_bonus(self, kind, cat):
            return self.pierce if (kind == "pierce" and cat == "damage") else 0.0

    class Titles:
        def __init__(self, crit): self.crit = crit
        def get_total_bonus(self, key):
            return self.crit if key == "criticalChance" else 0.0

    cases = []
    for luck in [0, 1, 5, 10, 30]:
        for pierce in [0.0, 0.15]:
            for title in [0.0, 0.05]:
                for tags in [None, ["precision"]]:
                    shim = SimpleNamespace(character=SimpleNamespace(
                        buffs=Buffs(pierce), titles=Titles(title),
                        get_effective_luck=lambda l=luck: float(l)))
                    chance = CombatManager._player_crit_chance(shim, weapon_tags=tags)
                    cases.append({"effective_luck": luck, "pierce_buff": pierce,
                                  "title_crit": title,
                                  "weapon_tags": tags or [], "chance": chance})
    write("crit_chance.json", {
        "_meta": meta("Combat/combat_manager.py::_player_crit_chance "
                      "(real method executed via shim; weapon-tag bonus via real "
                      "WeaponTagModifiers)"),
        "lck_crit_per_point": _LCK_CRIT_PER_POINT,
        "cases": cases,
    })


# ── 4. Defense reduction (transcribed seam — superseded by crux parity, P4) ──
def gen_defense_reduction() -> None:
    cases = []
    for defense in [0, 10, 50, 74, 75, 76, 80, 100, 500]:
        for pen in [0.0, 0.25, 0.5, 1.0]:
            effective = defense * (1.0 - pen)
            reduction = min(0.75, effective * 0.01)
            cases.append({"defense": defense, "armor_penetration": pen,
                          "reduction": reduction,
                          "damage_multiplier": 1.0 - reduction})
    write("defense_reduction.json", {
        "_meta": meta("core/effect_executor.py:162-168 (_apply_enemy_defense seam)",
                      note="TRANSCRIBED from the inline executor code (F5 fix); "
                           "upgrade to executed-path via crux-foundry parity in Phase 4"),
        "cap": 0.75,
        "per_point": 0.01,
        "cases": cases,
    })


# ── 5. Damage composition (action path, transcribed order — P4 supersedes) ───
def gen_damage_composition() -> None:
    from Combat.combat_manager import _STR_DMG_PER_POINT, _LCK_CRIT_PER_POINT

    def compose(base, weapon, hand_mult, strength, title_melee, enemy_mult,
                intelligence, elemental, crushing, enemy_def, empower, crit,
                armor_pen):
        d = float(base)
        wd = weapon * hand_mult
        if wd > 0:
            d += wd
        d *= 1.0 + strength * _STR_DMG_PER_POINT
        d *= 1.0 + title_melee
        d *= enemy_mult
        if elemental:
            int_mult = 1.0 + intelligence * 0.05
            if int_mult > 1.0:
                d *= int_mult
        if crushing > 0 and enemy_def > 10:
            d *= 1.0 + crushing
        if empower > 0:
            d *= 1.0 + empower
        if crit:
            d *= 2.0
        effective = enemy_def * (1.0 - armor_pen)
        reduction = min(0.75, effective * 0.01)
        return d * (1.0 - reduction)

    base_case = dict(base=10, weapon=25, hand_mult=1.0, strength=0, title_melee=0.0,
                     enemy_mult=1.0, intelligence=0, elemental=False, crushing=0.0,
                     enemy_def=0, empower=0.0, crit=False, armor_pen=0.0)
    variants = [
        {},
        {"strength": 10},
        {"hand_mult": 1.2},
        {"title_melee": 0.10},
        {"enemy_mult": 1.15},
        {"intelligence": 10, "elemental": True},
        {"intelligence": 10, "elemental": False},
        {"crushing": 0.25, "enemy_def": 50},
        {"crushing": 0.25, "enemy_def": 5},
        {"empower": 0.5},
        {"crit": True},
        {"enemy_def": 50},
        {"enemy_def": 100, "armor_pen": 0.5},
        {"strength": 30, "hand_mult": 1.2, "title_melee": 0.1, "enemy_mult": 1.15,
         "intelligence": 30, "elemental": True, "crushing": 0.25, "enemy_def": 120,
         "empower": 0.5, "crit": True, "armor_pen": 0.25},
    ]
    cases = []
    for v in variants:
        inputs = {**base_case, **v}
        cases.append({"inputs": inputs, "final_damage": compose(**inputs)})
    write("damage_composition.json", {
        "_meta": meta("Combat/combat_manager.py::player_attack_enemy_with_tags "
                      "lines ~1608-1692 + executor defense seam",
                      note="TRANSCRIBED multiplier order (verified against code "
                           "2026-07-17); superseded by crux-foundry scenario parity "
                           "in Phase 4. Order: (+weapon*hand) *STR *titleMelee "
                           "*enemyTitle *INT-elemental(tag-gated) *crushing(def>10) "
                           "*empower *crit(2.0) -> per-target defense"),
        "str_dmg_per_point": _STR_DMG_PER_POINT,
        "lck_crit_per_point": _LCK_CRIT_PER_POINT,
        "cases": cases,
    })


# ── 6. Difficulty calculator (real functions, real MaterialDatabase) ─────────
def gen_difficulty() -> None:
    import core.difficulty_calculator as dc
    from data.databases.material_db import MaterialDatabase

    mat_db = MaterialDatabase.get_instance()
    if not mat_db.loaded:
        mat_db.load_from_files()  # the sacred boot sequence + generated overlay

    by_tier = {}
    for mid, mat in sorted(getattr(mat_db, "materials", {}).items()):
        by_tier.setdefault(getattr(mat, "tier", 1), []).append(mid)
    samples = {t: ids[:2] for t, ids in sorted(by_tier.items())}

    def mk(spec):  # spec: list of (tier, qty); tier included for the C# tier resolver
        return [{"materialId": samples[t][0], "quantity": q, "tier": t}
                for (t, q) in spec if t in samples and samples[t]]

    input_sets = {
        "t1_single": mk([(1, 3)]),
        "t1_pair": mk([(1, 2), (1, 1)]) if len(samples.get(1, [])) < 2 else
                   [{"materialId": samples[1][0], "quantity": 2},
                    {"materialId": samples[1][1], "quantity": 1}],
        "t2_mix": mk([(1, 2), (2, 2)]),
        "t3_heavy": mk([(3, 4), (2, 2), (1, 1)]),
        "t4_epic": mk([(4, 5), (3, 3)]),
        "empty": [],
    }

    core = {name: {
        "inputs": inputs,
        "material_points": dc.calculate_material_points(inputs),
        "diversity_multiplier": dc.calculate_diversity_multiplier(inputs),
        "average_tier": dc.calculate_average_tier(inputs),
    } for name, inputs in input_sets.items()}

    disciplines = {}
    for disc, fn in [("smithing", dc.calculate_smithing_difficulty),
                     ("refining", dc.calculate_refining_difficulty),
                     ("alchemy", dc.calculate_alchemy_difficulty),
                     ("engineering", dc.calculate_engineering_difficulty),
                     ("enchanting", dc.calculate_enchanting_difficulty)]:
        disciplines[disc] = {}
        for name, inputs in input_sets.items():
            if not inputs:
                continue
            recipe = {"inputs": inputs, "stationTier": 2, "station_tier": 2,
                      "recipeId": f"golden_{disc}_{name}"}
            try:
                disciplines[disc][name] = fn(recipe)
            except Exception as e:  # surfaced, never silently skipped
                disciplines[disc][name] = {"_error": f"{type(e).__name__}: {e}"}

    tier_bands = {str(p): dc.get_difficulty_tier(p)
                  for p in [0, 1, 4, 4.9, 5, 10, 10.9, 11, 20, 21, 40, 41, 60, 100]}

    write("difficulty.json", {
        "_meta": meta("core/difficulty_calculator.py (module functions executed "
                      "against the live MaterialDatabase)"),
        "material_samples_by_tier": {str(k): v for k, v in samples.items()},
        "materials_loaded": len(getattr(mat_db, "materials", {})),
        "core_calculations": core,
        "discipline_difficulty": disciplines,
        "difficulty_tier_bands": tier_bands,
    })


# ── 7. Reward calculator (pure functions) ────────────────────────────────────
def gen_rewards() -> None:
    import core.reward_calculator as rc

    performances = [0.0, 0.1, 0.24, 0.25, 0.26, 0.5, 0.74, 0.75, 0.9, 0.99, 1.0]
    points = [1, 4, 5, 10, 11, 20, 21, 40, 41, 60, 100]

    quality = {str(p): rc.get_quality_tier(p) for p in performances}
    max_mult = {str(pt): rc.calculate_max_reward_multiplier(pt) for pt in points}

    grids = []
    for p in performances:
        for pt in [1, 11, 41]:
            mm = rc.calculate_max_reward_multiplier(pt)
            grids.append({"performance": p, "difficulty_points": pt,
                          "max_multiplier": mm,
                          "bonus_pct": rc.calculate_bonus_pct(p, mm),
                          "stat_multiplier": rc.calculate_stat_multiplier(p, mm)})

    failure = {str(pt): rc.calculate_failure_penalty(pt) for pt in points}
    loss_sample = rc.calculate_material_loss(
        [{"materialId": "iron_ore", "quantity": 10},
         {"materialId": "oak_wood", "quantity": 3},
         {"materialId": "coal", "quantity": 1}], 25.0)
    first_try = {(d or "default"): rc.first_try_bonus(d) for d in
                 ["", "smithing", "alchemy", "refining", "engineering",
                  "enchanting", "fishing"]}

    write("rewards.json", {
        "_meta": meta("core/reward_calculator.py (module functions executed)"),
        "quality_tier_by_performance": quality,
        "max_multiplier_by_points": max_mult,
        "bonus_and_stat_multiplier_grid": grids,
        "failure_penalty_by_points": failure,
        "material_loss_sample_at_25pts": loss_sample,
        "first_try_bonus_by_discipline": first_try,
    })


if __name__ == "__main__":
    print(f"Golden generation @ {SHA} (source: {SRC})")
    gen_exp_curve()
    gen_stat_scaling()
    gen_crit_chance()
    gen_defense_reduction()
    gen_damage_composition()
    gen_difficulty()
    gen_rewards()
    print("done.")
