"""
Together.ai Fine-Tuning Script for Crafting Models

Launches fine-tuning jobs on Together.ai with train/validation split.

Usage:
    python together_finetune.py

Prerequisites:
    pip install together

Generated by convert_to_jsonl.py:
    - jsonl_outputs/train.jsonl (80% of data)
    - jsonl_outputs/validation.jsonl (20% of data)
"""

import os
import json
from pathlib import Path

# =============================================================================
# CONFIGURATION
# =============================================================================

# Default model for fine-tuning (change as needed)
MODEL = "meta-llama/Llama-3.2-3B-Instruct"

# Training/validation file paths (relative to this script)
TRAINING_FILE = "./jsonl_outputs/train.jsonl"
VALIDATION_FILE = "./jsonl_outputs/validation.jsonl"

# Training parameters
N_EPOCHS = 3
LEARNING_RATE = 1e-5
BATCH_SIZE = 4
LORA = True
SUFFIX = "crafting-v1"


# =============================================================================
# MAIN
# =============================================================================

def get_api_key() -> str:
    """Get API key from environment or prompt user."""
    api_key = os.environ.get("TOGETHER_API_KEY")

    if not api_key:
        print("TOGETHER_API_KEY not found in environment.")
        api_key = input("Enter your Together.ai API key: ").strip()

        if not api_key:
            print("Error: API key is required.")
            exit(1)

        os.environ["TOGETHER_API_KEY"] = api_key

    return api_key


def count_jsonl_entries(filepath: Path) -> int:
    """Count entries in a JSONL file."""
    with open(filepath) as f:
        return sum(1 for _ in f)


def main():
    print("=" * 60)
    print("Together.ai Fine-Tuning for Crafting Models")
    print("=" * 60)

    script_dir = Path(__file__).parent
    training_path = script_dir / TRAINING_FILE
    validation_path = script_dir / VALIDATION_FILE

    # Check files exist
    if not training_path.exists():
        print(f"\nError: Training file not found: {training_path}")
        print("Run convert_to_jsonl.py first to generate training data.")
        return

    # Count entries
    train_count = count_jsonl_entries(training_path)
    val_count = 0
    if validation_path.exists():
        val_count = count_jsonl_entries(validation_path)

    print(f"\nDataset:")
    print(f"  Training: {training_path.name} ({train_count} entries)")
    if val_count > 0:
        print(f"  Validation: {validation_path.name} ({val_count} entries)")
    else:
        print(f"  Validation: Not provided")

    print(f"\nConfiguration:")
    print(f"  Model: {MODEL}")
    print(f"  Epochs: {N_EPOCHS}")
    print(f"  Learning rate: {LEARNING_RATE}")
    print(f"  Batch size: {BATCH_SIZE}")
    print(f"  LoRA: {LORA}")
    print(f"  Suffix: {SUFFIX}")

    # Get API key
    get_api_key()

    # Import together (after API key is set)
    try:
        from together import Together
    except ImportError:
        print("\nError: together package not installed.")
        print("Run: pip install together")
        return

    client = Together()

    # Confirm before proceeding
    print()
    confirm = input("Start fine-tuning job? (y/n): ").strip().lower()
    if confirm != 'y':
        print("Cancelled.")
        return

    # Upload training file
    print("\nUploading training file...")
    train_resp = client.files.upload(str(training_path), check=True)
    train_file_id = train_resp.id
    print(f"  Training file uploaded: {train_file_id}")

    # Upload validation file if exists
    val_file_id = None
    if validation_path.exists():
        print("Uploading validation file...")
        val_resp = client.files.upload(str(validation_path), check=True)
        val_file_id = val_resp.id
        print(f"  Validation file uploaded: {val_file_id}")

    # Create fine-tuning job
    print("\nStarting fine-tuning job...")
    job_params = {
        "training_file": train_file_id,
        "model": MODEL,
        "n_epochs": N_EPOCHS,
        "learning_rate": LEARNING_RATE,
        "batch_size": BATCH_SIZE,
        "lora": LORA,
        "suffix": SUFFIX,
    }

    if val_file_id:
        job_params["validation_file"] = val_file_id

    job_resp = client.fine_tuning.create(**job_params)

    job_id = job_resp.id
    print(f"\nJob started successfully!")
    print(f"  Job ID: {job_id}")
    print(f"  Monitor at: https://api.together.xyz/playground")
    print(f"\nTo check status:")
    print(f"  together fine-tuning retrieve {job_id}")


if __name__ == "__main__":
    main()
