// ============================================================================
// Game1.Systems.LLM.GeneratedItem
// Migrated from: systems/llm_item_generator.py (GeneratedItem dataclass, lines 322-345)
// Migration phase: 7
// Date: 2026-02-14
//
// Result of an item generation attempt (either LLM or stub).
// Contains the full item definition if successful, or an error message.
// ============================================================================

using System;
using System.Collections.Generic;

namespace Game1.Systems.LLM
{
    /// <summary>
    /// Result of an item generation attempt (either LLM or stub).
    /// Contains the full item definition if successful, or an error message.
    /// </summary>
    [Serializable]
    public class GeneratedItem
    {
        /// <summary>Whether item generation succeeded.</summary>
        public bool Success { get; set; }

        /// <summary>Full item definition matching game JSON schema. Null on failure.</summary>
        public Dictionary<string, object> ItemData { get; set; }

        /// <summary>Unique item identifier (e.g., "invented_smithing_abc123").</summary>
        public string ItemId { get; set; }

        /// <summary>Display name for the generated item.</summary>
        public string ItemName { get; set; }

        /// <summary>Crafting discipline that produced this item.</summary>
        public string Discipline { get; set; } = "";

        /// <summary>Error message if generation failed. Null on success.</summary>
        public string Error { get; set; }

        /// <summary>Whether this result came from cache rather than fresh generation.</summary>
        public bool FromCache { get; set; }

        /// <summary>Recipe inputs for save system persistence.</summary>
        public List<Dictionary<string, object>> RecipeInputs { get; set; }

        /// <summary>Station tier used for crafting.</summary>
        public int StationTier { get; set; } = 1;

        /// <summary>Lore/flavor text for the item.</summary>
        public string Narrative { get; set; } = "";

        /// <summary>Whether this item was generated by a stub (not a real LLM).</summary>
        public bool IsStub { get; set; }

        /// <summary>Whether the generation succeeded and produced valid item data.</summary>
        public bool IsValid => Success && ItemData != null;

        /// <summary>Whether the generation failed.</summary>
        public bool IsError => !Success;

        /// <summary>Create a successful GeneratedItem.</summary>
        public static GeneratedItem CreateSuccess(
            Dictionary<string, object> itemData,
            string itemId,
            string itemName,
            string discipline,
            bool isStub = false)
        {
            return new GeneratedItem
            {
                Success = true,
                ItemData = itemData,
                ItemId = itemId,
                ItemName = itemName,
                Discipline = discipline,
                IsStub = isStub
            };
        }

        /// <summary>Create a failed GeneratedItem with an error message.</summary>
        public static GeneratedItem CreateError(string discipline, string error)
        {
            return new GeneratedItem
            {
                Success = false,
                Discipline = discipline,
                Error = error
            };
        }
    }
}
