using System;
using System.Collections.Generic;
using Game1.Core.World;
using Game1.Core.World.Geography;
using Godot;

namespace Game1.Godot;

/// <summary>
/// The ONE shared spatial model for a streamed world window.
///
/// The world used to be generated by a dozen independent Build* passes, each
/// re-deriving biome / height / slope / road-clearance on its own, with its own
/// radius — and split across two DISAGREEING entry points (a rich static core vs a
/// cruder streamed frontier). That divergence is exactly why the world read as
/// "pieced together". This context is the fix: every placer — terrain, villages,
/// resources, ground cover, NPCs, enemies — asks the SAME object for the SAME
/// masks, so one coherent rule set builds the whole world, identically in the
/// settled core and out on the frontier. Rebuilt fresh each time the window
/// recenters on the player.
///
/// Masks it owns:
///   • biome / danger — ChunkType/Danger/GeoInfo from the certified geography
///     (falling back to the legacy biome generator where no geography exists);
///   • terrain — Height/MeshHeight/IsWater/Slope, all through TerrainHeightField
///     (the single elevation source of truth);
///   • road corridor — RoadClear(x,z,extra): is a point outside every nearby
///     road's width-scaled verge, tested by the object's EDGE (its own radius),
///     not just its centre;
///   • occupancy (Poisson-disk) — TryOccupy(x,z,min): reserve a spot only if
///     nothing already sits within min distance, so nothing overlaps into piles;
///     villages Reserve() their footprint first so nothing spawns in a building;
///   • window — ChunkInWindow / bounds for the streamed region.
/// </summary>
public sealed class WorldContext
{
    public readonly int CenterCX, CenterCY;
    public readonly int ChunkRadius;     // terrain / scatter / village reach
    public readonly int ResourceRadius;  // harvestable-resource reach
    public readonly int ChunkSize;
    public readonly long Seed;

    private readonly WorldMap? _map;
    private readonly BiomeGenerator _biomes;
    private readonly RoadNetwork? _roadNet;

    // road-clearance segments crossing the window, each with a width-scaled verge.
    private readonly List<(Vector2 A, Vector2 B, float Clear)> _roadSegs = new();
    private static readonly float[] RoadWidth = { 1.0f, 1.9f, 3.2f, 5.0f };

    // minimum-spacing occupancy hash (a cheap Poisson-disk gate).
    private readonly Dictionary<(int, int), List<Vector2>> _occ = new();
    private const float OccCell = 5.0f;

    public WorldContext(int centerCX, int centerCY, int chunkRadius, int resourceRadius,
                        int chunkSize, long seed, WorldMap? map, BiomeGenerator biomes,
                        RoadNetwork? roadNet)
    {
        CenterCX = centerCX; CenterCY = centerCY;
        ChunkRadius = chunkRadius; ResourceRadius = resourceRadius;
        ChunkSize = chunkSize; Seed = seed;
        _map = map; _biomes = biomes; _roadNet = roadNet;
        CollectRoadSegments();
    }

    // ---------------------------------------------------------- biome / danger ---

    /// <summary>Chunk biome type — the certified geographic chunk type where the
    /// world has geography, else the legacy biome generator.</summary>
    public string ChunkType(int cx, int cy) =>
        _map?.GetChunkData(cx, cy)?.ChunkType ?? _biomes.GetChunkType(cx, cy);

    /// <summary>Geographic danger level (3 where no geography exists).</summary>
    public int Danger(int cx, int cy) =>
        _map?.GetChunkData(cx, cy) is { } g ? (int)g.DangerLevel : 3;

    /// <summary>Raw geographic (type, danger) for the certified chunk generator —
    /// (null, null) where the chunk has no geography.</summary>
    public (string? Type, int? Danger) GeoInfo(int cx, int cy) =>
        _map?.GetChunkData(cx, cy) is { } g ? (g.ChunkType, (int)g.DangerLevel) : (null, null);

    public long ChunkSeed(int cx, int cy) => _biomes.GetChunkSeed(cx, cy);

    // ------------------------------------------------------------ terrain queries ---
    // One elevation source of truth: TerrainHeightField. Placers never sample the
    // field directly, so height/water/slope stay consistent across every system.

    public float Height(double x, double z) => TerrainHeightField.H(x, z);
    public float MeshHeight(double x, double z) => TerrainHeightField.HMesh(x, z);
    public bool IsWater(double x, double z) => TerrainHeightField.IsWater(x, z);

    /// <summary>Terrain steepness in [0,1] (0 flat, →1 sheer) from the height
    /// gradient — resources/props avoid cliffs by querying this.</summary>
    public float Slope(double x, double z)
    {
        var hl = TerrainHeightField.H(x - 1, z);
        var hr = TerrainHeightField.H(x + 1, z);
        var hd = TerrainHeightField.H(x, z - 1);
        var hu = TerrainHeightField.H(x, z + 1);
        return 1f - new Vector3((float)(hl - hr), 2f, (float)(hd - hu)).Normalized().Y;
    }

    // -------------------------------------------------------------- window bounds ---

    public bool ChunkInWindow(int cx, int cy) =>
        Math.Abs(cx - CenterCX) <= ChunkRadius && Math.Abs(cy - CenterCY) <= ChunkRadius;

    /// <summary>Does any of a settlement's chunks fall inside this streamed window?
    /// (Villages/NPCs render only for settlements whose footprint is in view — the
    /// same test in the core and the frontier, so the frontier gets settlements
    /// too instead of the old origin-only check.)</summary>
    public bool AnyChunkInWindow(IEnumerable<(int X, int Y)> chunks)
    {
        foreach (var c in chunks)
            if (ChunkInWindow(c.X, c.Y)) return true;
        return false;
    }

    // ------------------------------------------------------------ road clearance ---

    /// <summary>Gather road segments crossing the window, each with a width-scaled
    /// clearance verge (arteries get grand margins, feeders a thin one). The object's
    /// own radius is added at query time so its EDGE clears the road, not just its
    /// centre.
    ///
    /// CRITICAL: this ROUTES each near-window edge (the same lazy, cached
    /// RoadRouter.Route the terrain-grade and ribbon passes use) so clearance follows
    /// the ACTUAL curved road. It must not fall back to the straight A→B schematic —
    /// the router bends around lakes/hills by tens of tiles, and clearing the straight
    /// line while the ribbon draws the curve is exactly what put trees/rocks/walls on
    /// top of the visible road. Routing is cached on the shared edge, so a window that
    /// touches an already-routed edge pays nothing.</summary>
    private void CollectRoadSegments()
    {
        _roadSegs.Clear();
        if (_roadNet is null) return;
        var r = Math.Max(ChunkRadius, ResourceRadius);
        float minX = (CenterCX - r - 3) * ChunkSize, maxX = (CenterCX + r + 4) * ChunkSize;
        float minY = (CenterCY - r - 3) * ChunkSize, maxY = (CenterCY + r + 4) * ChunkSize;
        bool NearWin(Vector2 a, Vector2 b) =>
            Math.Min(a.X, b.X) <= maxX && Math.Max(a.X, b.X) >= minX
            && Math.Min(a.Y, b.Y) <= maxY && Math.Max(a.Y, b.Y) >= minY;

        foreach (var e in _roadNet.Edges)
        {
            // Cheap straight-endpoint reject (a routed path only bows near the window
            // if the straight span already passes near it — same filter the grade/draw
            // passes use). Then route so clearance follows the real curve.
            if (!NearWin(e.A, e.B)) continue;
            if (!e.Routed) { e.Path = RoadRouter.Route(e.A, e.B, e.Tier); e.Routed = true; }
            var clear = RoadWidth[e.Tier] * 1.4f;
            if (e.Path is { Length: >= 2 } path)
            {
                for (var i = 0; i < path.Length - 1; i++)
                    if (NearWin(path[i], path[i + 1]))
                        _roadSegs.Add((path[i], path[i + 1], clear));
            }
            else
                _roadSegs.Add((e.A, e.B, clear));   // router degenerate → straight
        }
    }

    /// <summary>True when (x,z) — expanded by the object's own radius <paramref
    /// name="extra"/> so its EDGE (not its centre) must clear — is outside every
    /// nearby road's clearance corridor.</summary>
    public bool RoadClear(double x, double z, float extra = 0f)
    {
        var p = new Vector2((float)x, (float)z);
        foreach (var (a, b, clear) in _roadSegs)
            if (DistToSeg(p, a, b) < clear + extra) return false;
        return true;
    }

    private static float DistToSeg(Vector2 p, Vector2 a, Vector2 b)
    {
        var ab = b - a;
        var len2 = ab.LengthSquared();
        var t = len2 < 1e-6f ? 0f : Mathf.Clamp((p - a).Dot(ab) / len2, 0f, 1f);
        return p.DistanceTo(a + ab * t);
    }

    // --------------------------------------------------------- occupancy (Poisson) ---

    /// <summary>Reserve a spot if nothing already sits within minDist — a cheap
    /// Poisson-disk gate that stops placements from overlapping into clumps.</summary>
    public bool TryOccupy(double x, double z, float minDist)
    {
        var p = new Vector2((float)x, (float)z);
        int cx = (int)Math.Floor(x / OccCell), cy = (int)Math.Floor(z / OccCell);
        var min2 = minDist * minDist;
        for (var dy = -1; dy <= 1; dy++)
            for (var dx = -1; dx <= 1; dx++)
                if (_occ.TryGetValue((cx + dx, cy + dy), out var list))
                    foreach (var q in list)
                        if (p.DistanceSquaredTo(q) < min2) return false;
        if (!_occ.TryGetValue((cx, cy), out var cell)) _occ[(cx, cy)] = cell = new();
        cell.Add(p);
        return true;
    }

    /// <summary>Seed an occupied spot (village walls/buildings) so later placements
    /// keep clear of it. Same store as TryOccupy — one occupancy model for all.</summary>
    public void Reserve(double x, double z, float radius) => TryOccupy(x, z, radius);

    /// <summary>Non-mutating: is anything already reserved within <paramref
    /// name="radius"/> of (x,z)? Ground cover uses this to stay out of buildings and
    /// off resource footprints (villages + resources both live in the occupancy
    /// store). Radius must be ≤ the occupancy cell (5) for the 3×3 scan to be exact.</summary>
    public bool IsReserved(double x, double z, float radius)
    {
        var p = new Vector2((float)x, (float)z);
        int cx = (int)Math.Floor(x / OccCell), cy = (int)Math.Floor(z / OccCell);
        var r2 = radius * radius;
        for (var dy = -1; dy <= 1; dy++)
            for (var dx = -1; dx <= 1; dx++)
                if (_occ.TryGetValue((cx + dx, cy + dy), out var list))
                    foreach (var q in list)
                        if (p.DistanceSquaredTo(q) < r2) return true;
        return false;
    }

    // ------------------------------------------------------------------ stations ---
    // The 20 free starter stations (5 columns × 4 tiers) are an origin fixture
    // (world_system.py:671-692) — GLOBAL, never streamed. Placement everywhere
    // yields their footprint so a station never spawns half-buried in a resource.
    private static readonly (int X, int Y)[] StationTiles = BuildStationTiles();

    private static (int X, int Y)[] BuildStationTiles()
    {
        var list = new List<(int, int)>();
        foreach (var x in new[] { -8, -4, 0, 4, 8 })
            for (var tier = 1; tier <= 4; tier++)
                list.Add((x, -10 - (tier - 1) * 2));
        return list.ToArray();
    }

    public static bool NearStation(double x, double z, float r)
    {
        foreach (var (sx, sy) in StationTiles)
        {
            var dx = x - (sx + 0.5); var dy = z - (sy + 0.5);
            if (dx * dx + dy * dy < r * r) return true;
        }
        return false;
    }
}
